import numpy as np
import cv2 as cv
from pygrabber.dshow_graph import FilterGraph



def find_all_caps():
    caps = ""
    for cap in dir(cv):
        if "CAP" in cap:
            caps += f"('{str(cap)}', cv.{cap}),\n"
    
    print("------ALL CAPS------")
    print(caps)
    print("------ALL CAPS------")



def draw_info(cap, img, values):
   
    h = img.shape[0]*2
    w = img.shape[1]*2
    
    blank = np.full((h, w, 3), [255, 255, 255], np.uint8)
    blank[0:img.shape[0], 0:img.shape[1]] = img

    for idx, (name, prop) in enumerate(values):
        val = cap.get(prop)
        cv.putText(blank, f"{name}:{val}", (w-500, 22*(idx+1)), cv.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 2, cv.LINE_AA)
        
    return blank


def is_cap_writable(cap, values):
    print("------WRITABLE CAPS------")
    for name, val in values:
        retval = cap.get(val)
        try:
            is_writable = cap.set(val, retval)
            if is_writable:
                print(f"('{str(name)}', cv.{name}),")
        except:
            pass
    print("------WRITABLE CAPS------")    
      
            
  
        
#find_all_caps()

ALL_CAPS = [
('CAP_ANDROID', cv.CAP_ANDROID),
('CAP_ANY', cv.CAP_ANY),
('CAP_ARAVIS', cv.CAP_ARAVIS),
('CAP_AVFOUNDATION', cv.CAP_AVFOUNDATION),
('CAP_CMU1394', cv.CAP_CMU1394),
('CAP_DC1394', cv.CAP_DC1394),
('CAP_DSHOW', cv.CAP_DSHOW),
('CAP_FFMPEG', cv.CAP_FFMPEG),
('CAP_FIREWARE', cv.CAP_FIREWARE),
('CAP_FIREWIRE', cv.CAP_FIREWIRE),
('CAP_GIGANETIX', cv.CAP_GIGANETIX),
('CAP_GPHOTO2', cv.CAP_GPHOTO2),
('CAP_GSTREAMER', cv.CAP_GSTREAMER),
('CAP_IEEE1394', cv.CAP_IEEE1394),
('CAP_IMAGES', cv.CAP_IMAGES),
('CAP_INTELPERC', cv.CAP_INTELPERC),
('CAP_INTELPERC_DEPTH_GENERATOR', cv.CAP_INTELPERC_DEPTH_GENERATOR),
('CAP_INTELPERC_DEPTH_MAP', cv.CAP_INTELPERC_DEPTH_MAP),
('CAP_INTELPERC_GENERATORS_MASK', cv.CAP_INTELPERC_GENERATORS_MASK),
('CAP_INTELPERC_IMAGE', cv.CAP_INTELPERC_IMAGE),
('CAP_INTELPERC_IMAGE_GENERATOR', cv.CAP_INTELPERC_IMAGE_GENERATOR),
('CAP_INTELPERC_IR_GENERATOR', cv.CAP_INTELPERC_IR_GENERATOR),
('CAP_INTELPERC_IR_MAP', cv.CAP_INTELPERC_IR_MAP),
('CAP_INTELPERC_UVDEPTH_MAP', cv.CAP_INTELPERC_UVDEPTH_MAP),
('CAP_INTEL_MFX', cv.CAP_INTEL_MFX),
('CAP_MSMF', cv.CAP_MSMF),
('CAP_OBSENSOR', cv.CAP_OBSENSOR),
('CAP_OBSENSOR_BGR_IMAGE', cv.CAP_OBSENSOR_BGR_IMAGE),
('CAP_OBSENSOR_DEPTH_GENERATOR', cv.CAP_OBSENSOR_DEPTH_GENERATOR),
('CAP_OBSENSOR_DEPTH_MAP', cv.CAP_OBSENSOR_DEPTH_MAP),
('CAP_OBSENSOR_GENERATORS_MASK', cv.CAP_OBSENSOR_GENERATORS_MASK),
('CAP_OBSENSOR_IMAGE_GENERATOR', cv.CAP_OBSENSOR_IMAGE_GENERATOR),
('CAP_OBSENSOR_IR_GENERATOR', cv.CAP_OBSENSOR_IR_GENERATOR),
('CAP_OBSENSOR_IR_IMAGE', cv.CAP_OBSENSOR_IR_IMAGE),
('CAP_OPENCV_MJPEG', cv.CAP_OPENCV_MJPEG),
('CAP_OPENNI', cv.CAP_OPENNI),
('CAP_OPENNI2', cv.CAP_OPENNI2),
('CAP_OPENNI2_ASTRA', cv.CAP_OPENNI2_ASTRA),
('CAP_OPENNI2_ASUS', cv.CAP_OPENNI2_ASUS),
('CAP_OPENNI_ASUS', cv.CAP_OPENNI_ASUS),
('CAP_OPENNI_BGR_IMAGE', cv.CAP_OPENNI_BGR_IMAGE),
('CAP_OPENNI_DEPTH_GENERATOR', cv.CAP_OPENNI_DEPTH_GENERATOR),
('CAP_OPENNI_DEPTH_GENERATOR_BASELINE', cv.CAP_OPENNI_DEPTH_GENERATOR_BASELINE),
('CAP_OPENNI_DEPTH_GENERATOR_FOCAL_LENGTH', cv.CAP_OPENNI_DEPTH_GENERATOR_FOCAL_LENGTH),
('CAP_OPENNI_DEPTH_GENERATOR_PRESENT', cv.CAP_OPENNI_DEPTH_GENERATOR_PRESENT),
('CAP_OPENNI_DEPTH_GENERATOR_REGISTRATION', cv.CAP_OPENNI_DEPTH_GENERATOR_REGISTRATION),
('CAP_OPENNI_DEPTH_GENERATOR_REGISTRATION_ON', cv.CAP_OPENNI_DEPTH_GENERATOR_REGISTRATION_ON),
('CAP_OPENNI_DEPTH_MAP', cv.CAP_OPENNI_DEPTH_MAP),
('CAP_OPENNI_DISPARITY_MAP', cv.CAP_OPENNI_DISPARITY_MAP),
('CAP_OPENNI_DISPARITY_MAP_32F', cv.CAP_OPENNI_DISPARITY_MAP_32F),
('CAP_OPENNI_GENERATORS_MASK', cv.CAP_OPENNI_GENERATORS_MASK),
('CAP_OPENNI_GRAY_IMAGE', cv.CAP_OPENNI_GRAY_IMAGE),
('CAP_OPENNI_IMAGE_GENERATOR', cv.CAP_OPENNI_IMAGE_GENERATOR),
('CAP_OPENNI_IMAGE_GENERATOR_OUTPUT_MODE', cv.CAP_OPENNI_IMAGE_GENERATOR_OUTPUT_MODE),
('CAP_OPENNI_IMAGE_GENERATOR_PRESENT', cv.CAP_OPENNI_IMAGE_GENERATOR_PRESENT),
('CAP_OPENNI_IR_GENERATOR', cv.CAP_OPENNI_IR_GENERATOR),
('CAP_OPENNI_IR_GENERATOR_PRESENT', cv.CAP_OPENNI_IR_GENERATOR_PRESENT),
('CAP_OPENNI_IR_IMAGE', cv.CAP_OPENNI_IR_IMAGE),
('CAP_OPENNI_POINT_CLOUD_MAP', cv.CAP_OPENNI_POINT_CLOUD_MAP),
('CAP_OPENNI_QVGA_30HZ', cv.CAP_OPENNI_QVGA_30HZ),
('CAP_OPENNI_QVGA_60HZ', cv.CAP_OPENNI_QVGA_60HZ),
('CAP_OPENNI_SXGA_15HZ', cv.CAP_OPENNI_SXGA_15HZ),
('CAP_OPENNI_SXGA_30HZ', cv.CAP_OPENNI_SXGA_30HZ),
('CAP_OPENNI_VALID_DEPTH_MASK', cv.CAP_OPENNI_VALID_DEPTH_MASK),
('CAP_OPENNI_VGA_30HZ', cv.CAP_OPENNI_VGA_30HZ),
('CAP_PROP_ANDROID_DEVICE_TORCH', cv.CAP_PROP_ANDROID_DEVICE_TORCH),
('CAP_PROP_APERTURE', cv.CAP_PROP_APERTURE),
('CAP_PROP_ARAVIS_AUTOTRIGGER', cv.CAP_PROP_ARAVIS_AUTOTRIGGER),
('CAP_PROP_AUDIO_BASE_INDEX', cv.CAP_PROP_AUDIO_BASE_INDEX),
('CAP_PROP_AUDIO_DATA_DEPTH', cv.CAP_PROP_AUDIO_DATA_DEPTH),
('CAP_PROP_AUDIO_POS', cv.CAP_PROP_AUDIO_POS),
('CAP_PROP_AUDIO_SAMPLES_PER_SECOND', cv.CAP_PROP_AUDIO_SAMPLES_PER_SECOND),
('CAP_PROP_AUDIO_SHIFT_NSEC', cv.CAP_PROP_AUDIO_SHIFT_NSEC),
('CAP_PROP_AUDIO_STREAM', cv.CAP_PROP_AUDIO_STREAM),
('CAP_PROP_AUDIO_SYNCHRONIZE', cv.CAP_PROP_AUDIO_SYNCHRONIZE),
('CAP_PROP_AUDIO_TOTAL_CHANNELS', cv.CAP_PROP_AUDIO_TOTAL_CHANNELS),
('CAP_PROP_AUDIO_TOTAL_STREAMS', cv.CAP_PROP_AUDIO_TOTAL_STREAMS),
('CAP_PROP_AUTOFOCUS', cv.CAP_PROP_AUTOFOCUS),
('CAP_PROP_AUTO_EXPOSURE', cv.CAP_PROP_AUTO_EXPOSURE),
('CAP_PROP_AUTO_WB', cv.CAP_PROP_AUTO_WB),
('CAP_PROP_BACKEND', cv.CAP_PROP_BACKEND),
('CAP_PROP_BACKLIGHT', cv.CAP_PROP_BACKLIGHT),
('CAP_PROP_BITRATE', cv.CAP_PROP_BITRATE),
('CAP_PROP_BRIGHTNESS', cv.CAP_PROP_BRIGHTNESS),
('CAP_PROP_BUFFERSIZE', cv.CAP_PROP_BUFFERSIZE),
('CAP_PROP_CHANNEL', cv.CAP_PROP_CHANNEL),
('CAP_PROP_CODEC_EXTRADATA_INDEX', cv.CAP_PROP_CODEC_EXTRADATA_INDEX),
('CAP_PROP_CODEC_PIXEL_FORMAT', cv.CAP_PROP_CODEC_PIXEL_FORMAT),
('CAP_PROP_CONTRAST', cv.CAP_PROP_CONTRAST),
('CAP_PROP_CONVERT_RGB', cv.CAP_PROP_CONVERT_RGB),
('CAP_PROP_DC1394_MAX', cv.CAP_PROP_DC1394_MAX),
('CAP_PROP_DC1394_MODE_AUTO', cv.CAP_PROP_DC1394_MODE_AUTO),
('CAP_PROP_DC1394_MODE_MANUAL', cv.CAP_PROP_DC1394_MODE_MANUAL),
('CAP_PROP_DC1394_MODE_ONE_PUSH_AUTO', cv.CAP_PROP_DC1394_MODE_ONE_PUSH_AUTO),
('CAP_PROP_DC1394_OFF', cv.CAP_PROP_DC1394_OFF),
('CAP_PROP_DTS_DELAY', cv.CAP_PROP_DTS_DELAY),
('CAP_PROP_EXPOSURE', cv.CAP_PROP_EXPOSURE),
('CAP_PROP_EXPOSUREPROGRAM', cv.CAP_PROP_EXPOSUREPROGRAM),
('CAP_PROP_FOCUS', cv.CAP_PROP_FOCUS),
('CAP_PROP_FORMAT', cv.CAP_PROP_FORMAT),
('CAP_PROP_FOURCC', cv.CAP_PROP_FOURCC),
('CAP_PROP_FPS', cv.CAP_PROP_FPS),
('CAP_PROP_FRAME_COUNT', cv.CAP_PROP_FRAME_COUNT),
('CAP_PROP_FRAME_HEIGHT', cv.CAP_PROP_FRAME_HEIGHT),
('CAP_PROP_FRAME_TYPE', cv.CAP_PROP_FRAME_TYPE),
('CAP_PROP_FRAME_WIDTH', cv.CAP_PROP_FRAME_WIDTH),
('CAP_PROP_GAIN', cv.CAP_PROP_GAIN),
('CAP_PROP_GAMMA', cv.CAP_PROP_GAMMA),
('CAP_PROP_GIGA_FRAME_HEIGH_MAX', cv.CAP_PROP_GIGA_FRAME_HEIGH_MAX),
('CAP_PROP_GIGA_FRAME_OFFSET_X', cv.CAP_PROP_GIGA_FRAME_OFFSET_X),
('CAP_PROP_GIGA_FRAME_OFFSET_Y', cv.CAP_PROP_GIGA_FRAME_OFFSET_Y),
('CAP_PROP_GIGA_FRAME_SENS_HEIGH', cv.CAP_PROP_GIGA_FRAME_SENS_HEIGH),
('CAP_PROP_GIGA_FRAME_SENS_WIDTH', cv.CAP_PROP_GIGA_FRAME_SENS_WIDTH),
('CAP_PROP_GIGA_FRAME_WIDTH_MAX', cv.CAP_PROP_GIGA_FRAME_WIDTH_MAX),
('CAP_PROP_GPHOTO2_COLLECT_MSGS', cv.CAP_PROP_GPHOTO2_COLLECT_MSGS),
('CAP_PROP_GPHOTO2_FLUSH_MSGS', cv.CAP_PROP_GPHOTO2_FLUSH_MSGS),
('CAP_PROP_GPHOTO2_PREVIEW', cv.CAP_PROP_GPHOTO2_PREVIEW),
('CAP_PROP_GPHOTO2_RELOAD_CONFIG', cv.CAP_PROP_GPHOTO2_RELOAD_CONFIG),
('CAP_PROP_GPHOTO2_RELOAD_ON_CHANGE', cv.CAP_PROP_GPHOTO2_RELOAD_ON_CHANGE),
('CAP_PROP_GPHOTO2_WIDGET_ENUMERATE', cv.CAP_PROP_GPHOTO2_WIDGET_ENUMERATE),
('CAP_PROP_GSTREAMER_QUEUE_LENGTH', cv.CAP_PROP_GSTREAMER_QUEUE_LENGTH),
('CAP_PROP_GUID', cv.CAP_PROP_GUID),
('CAP_PROP_HUE', cv.CAP_PROP_HUE),
('CAP_PROP_HW_ACCELERATION', cv.CAP_PROP_HW_ACCELERATION),
('CAP_PROP_HW_ACCELERATION_USE_OPENCL', cv.CAP_PROP_HW_ACCELERATION_USE_OPENCL),
('CAP_PROP_HW_DEVICE', cv.CAP_PROP_HW_DEVICE),
('CAP_PROP_IMAGES_BASE', cv.CAP_PROP_IMAGES_BASE),
('CAP_PROP_IMAGES_LAST', cv.CAP_PROP_IMAGES_LAST),
('CAP_PROP_INTELPERC_DEPTH_CONFIDENCE_THRESHOLD', cv.CAP_PROP_INTELPERC_DEPTH_CONFIDENCE_THRESHOLD),
('CAP_PROP_INTELPERC_DEPTH_FOCAL_LENGTH_HORZ', cv.CAP_PROP_INTELPERC_DEPTH_FOCAL_LENGTH_HORZ),
('CAP_PROP_INTELPERC_DEPTH_FOCAL_LENGTH_VERT', cv.CAP_PROP_INTELPERC_DEPTH_FOCAL_LENGTH_VERT),
('CAP_PROP_INTELPERC_DEPTH_LOW_CONFIDENCE_VALUE', cv.CAP_PROP_INTELPERC_DEPTH_LOW_CONFIDENCE_VALUE),
('CAP_PROP_INTELPERC_DEPTH_SATURATION_VALUE', cv.CAP_PROP_INTELPERC_DEPTH_SATURATION_VALUE),
('CAP_PROP_INTELPERC_PROFILE_COUNT', cv.CAP_PROP_INTELPERC_PROFILE_COUNT),
('CAP_PROP_INTELPERC_PROFILE_IDX', cv.CAP_PROP_INTELPERC_PROFILE_IDX),
('CAP_PROP_IOS_DEVICE_EXPOSURE', cv.CAP_PROP_IOS_DEVICE_EXPOSURE),
('CAP_PROP_IOS_DEVICE_FLASH', cv.CAP_PROP_IOS_DEVICE_FLASH),
('CAP_PROP_IOS_DEVICE_FOCUS', cv.CAP_PROP_IOS_DEVICE_FOCUS),
('CAP_PROP_IOS_DEVICE_TORCH', cv.CAP_PROP_IOS_DEVICE_TORCH),
('CAP_PROP_IOS_DEVICE_WHITEBALANCE', cv.CAP_PROP_IOS_DEVICE_WHITEBALANCE),
('CAP_PROP_IRIS', cv.CAP_PROP_IRIS),
('CAP_PROP_ISO_SPEED', cv.CAP_PROP_ISO_SPEED),
('CAP_PROP_LRF_HAS_KEY_FRAME', cv.CAP_PROP_LRF_HAS_KEY_FRAME),
('CAP_PROP_MODE', cv.CAP_PROP_MODE),
('CAP_PROP_MONOCHROME', cv.CAP_PROP_MONOCHROME),
('CAP_PROP_N_THREADS', cv.CAP_PROP_N_THREADS),
('CAP_PROP_OBSENSOR_INTRINSIC_CX', cv.CAP_PROP_OBSENSOR_INTRINSIC_CX),
('CAP_PROP_OBSENSOR_INTRINSIC_CY', cv.CAP_PROP_OBSENSOR_INTRINSIC_CY),
('CAP_PROP_OBSENSOR_INTRINSIC_FX', cv.CAP_PROP_OBSENSOR_INTRINSIC_FX),
('CAP_PROP_OBSENSOR_INTRINSIC_FY', cv.CAP_PROP_OBSENSOR_INTRINSIC_FY),
('CAP_PROP_OPENNI2_MIRROR', cv.CAP_PROP_OPENNI2_MIRROR),
('CAP_PROP_OPENNI2_SYNC', cv.CAP_PROP_OPENNI2_SYNC),
('CAP_PROP_OPENNI_APPROX_FRAME_SYNC', cv.CAP_PROP_OPENNI_APPROX_FRAME_SYNC),
('CAP_PROP_OPENNI_BASELINE', cv.CAP_PROP_OPENNI_BASELINE),
('CAP_PROP_OPENNI_CIRCLE_BUFFER', cv.CAP_PROP_OPENNI_CIRCLE_BUFFER),
('CAP_PROP_OPENNI_FOCAL_LENGTH', cv.CAP_PROP_OPENNI_FOCAL_LENGTH),
('CAP_PROP_OPENNI_FRAME_MAX_DEPTH', cv.CAP_PROP_OPENNI_FRAME_MAX_DEPTH),
('CAP_PROP_OPENNI_GENERATOR_PRESENT', cv.CAP_PROP_OPENNI_GENERATOR_PRESENT),
('CAP_PROP_OPENNI_MAX_BUFFER_SIZE', cv.CAP_PROP_OPENNI_MAX_BUFFER_SIZE),
('CAP_PROP_OPENNI_MAX_TIME_DURATION', cv.CAP_PROP_OPENNI_MAX_TIME_DURATION),
('CAP_PROP_OPENNI_OUTPUT_MODE', cv.CAP_PROP_OPENNI_OUTPUT_MODE),
('CAP_PROP_OPENNI_REGISTRATION', cv.CAP_PROP_OPENNI_REGISTRATION),
('CAP_PROP_OPENNI_REGISTRATION_ON', cv.CAP_PROP_OPENNI_REGISTRATION_ON),
('CAP_PROP_OPEN_TIMEOUT_MSEC', cv.CAP_PROP_OPEN_TIMEOUT_MSEC),
('CAP_PROP_ORIENTATION_AUTO', cv.CAP_PROP_ORIENTATION_AUTO),
('CAP_PROP_ORIENTATION_META', cv.CAP_PROP_ORIENTATION_META),
('CAP_PROP_PAN', cv.CAP_PROP_PAN),
('CAP_PROP_POS_AVI_RATIO', cv.CAP_PROP_POS_AVI_RATIO),
('CAP_PROP_POS_FRAMES', cv.CAP_PROP_POS_FRAMES),
('CAP_PROP_POS_MSEC', cv.CAP_PROP_POS_MSEC),
('CAP_PROP_PTS', cv.CAP_PROP_PTS),
('CAP_PROP_PVAPI_BINNINGX', cv.CAP_PROP_PVAPI_BINNINGX),
('CAP_PROP_PVAPI_BINNINGY', cv.CAP_PROP_PVAPI_BINNINGY),
('CAP_PROP_PVAPI_DECIMATIONHORIZONTAL', cv.CAP_PROP_PVAPI_DECIMATIONHORIZONTAL),
('CAP_PROP_PVAPI_DECIMATIONVERTICAL', cv.CAP_PROP_PVAPI_DECIMATIONVERTICAL),
('CAP_PROP_PVAPI_FRAMESTARTTRIGGERMODE', cv.CAP_PROP_PVAPI_FRAMESTARTTRIGGERMODE),
('CAP_PROP_PVAPI_MULTICASTIP', cv.CAP_PROP_PVAPI_MULTICASTIP),
('CAP_PROP_PVAPI_PIXELFORMAT', cv.CAP_PROP_PVAPI_PIXELFORMAT),
('CAP_PROP_READ_TIMEOUT_MSEC', cv.CAP_PROP_READ_TIMEOUT_MSEC),
('CAP_PROP_RECTIFICATION', cv.CAP_PROP_RECTIFICATION),
('CAP_PROP_ROLL', cv.CAP_PROP_ROLL),
('CAP_PROP_SAR_DEN', cv.CAP_PROP_SAR_DEN),
('CAP_PROP_SAR_NUM', cv.CAP_PROP_SAR_NUM),
('CAP_PROP_SATURATION', cv.CAP_PROP_SATURATION),
('CAP_PROP_SETTINGS', cv.CAP_PROP_SETTINGS),
('CAP_PROP_SHARPNESS', cv.CAP_PROP_SHARPNESS),
('CAP_PROP_SPEED', cv.CAP_PROP_SPEED),
('CAP_PROP_STREAM_OPEN_TIME_USEC', cv.CAP_PROP_STREAM_OPEN_TIME_USEC),
('CAP_PROP_TEMPERATURE', cv.CAP_PROP_TEMPERATURE),
('CAP_PROP_TILT', cv.CAP_PROP_TILT),
('CAP_PROP_TRIGGER', cv.CAP_PROP_TRIGGER),
('CAP_PROP_TRIGGER_DELAY', cv.CAP_PROP_TRIGGER_DELAY),
('CAP_PROP_VIDEO_STREAM', cv.CAP_PROP_VIDEO_STREAM),
('CAP_PROP_VIDEO_TOTAL_CHANNELS', cv.CAP_PROP_VIDEO_TOTAL_CHANNELS),
('CAP_PROP_VIEWFINDER', cv.CAP_PROP_VIEWFINDER),
('CAP_PROP_WB_TEMPERATURE', cv.CAP_PROP_WB_TEMPERATURE),
('CAP_PROP_WHITE_BALANCE_BLUE_U', cv.CAP_PROP_WHITE_BALANCE_BLUE_U),
('CAP_PROP_WHITE_BALANCE_RED_V', cv.CAP_PROP_WHITE_BALANCE_RED_V),
('CAP_PROP_XI_ACQ_BUFFER_SIZE', cv.CAP_PROP_XI_ACQ_BUFFER_SIZE),
('CAP_PROP_XI_ACQ_BUFFER_SIZE_UNIT', cv.CAP_PROP_XI_ACQ_BUFFER_SIZE_UNIT),
('CAP_PROP_XI_ACQ_FRAME_BURST_COUNT', cv.CAP_PROP_XI_ACQ_FRAME_BURST_COUNT),
('CAP_PROP_XI_ACQ_TIMING_MODE', cv.CAP_PROP_XI_ACQ_TIMING_MODE),
('CAP_PROP_XI_ACQ_TRANSPORT_BUFFER_COMMIT', cv.CAP_PROP_XI_ACQ_TRANSPORT_BUFFER_COMMIT),
('CAP_PROP_XI_ACQ_TRANSPORT_BUFFER_SIZE', cv.CAP_PROP_XI_ACQ_TRANSPORT_BUFFER_SIZE),
('CAP_PROP_XI_AEAG', cv.CAP_PROP_XI_AEAG),
('CAP_PROP_XI_AEAG_LEVEL', cv.CAP_PROP_XI_AEAG_LEVEL),
('CAP_PROP_XI_AEAG_ROI_HEIGHT', cv.CAP_PROP_XI_AEAG_ROI_HEIGHT),
('CAP_PROP_XI_AEAG_ROI_OFFSET_X', cv.CAP_PROP_XI_AEAG_ROI_OFFSET_X),
('CAP_PROP_XI_AEAG_ROI_OFFSET_Y', cv.CAP_PROP_XI_AEAG_ROI_OFFSET_Y),
('CAP_PROP_XI_AEAG_ROI_WIDTH', cv.CAP_PROP_XI_AEAG_ROI_WIDTH),
('CAP_PROP_XI_AE_MAX_LIMIT', cv.CAP_PROP_XI_AE_MAX_LIMIT),
('CAP_PROP_XI_AG_MAX_LIMIT', cv.CAP_PROP_XI_AG_MAX_LIMIT),
('CAP_PROP_XI_APPLY_CMS', cv.CAP_PROP_XI_APPLY_CMS),
('CAP_PROP_XI_AUTO_BANDWIDTH_CALCULATION', cv.CAP_PROP_XI_AUTO_BANDWIDTH_CALCULATION),
('CAP_PROP_XI_AUTO_WB', cv.CAP_PROP_XI_AUTO_WB),
('CAP_PROP_XI_AVAILABLE_BANDWIDTH', cv.CAP_PROP_XI_AVAILABLE_BANDWIDTH),
('CAP_PROP_XI_BINNING_HORIZONTAL', cv.CAP_PROP_XI_BINNING_HORIZONTAL),
('CAP_PROP_XI_BINNING_PATTERN', cv.CAP_PROP_XI_BINNING_PATTERN),
('CAP_PROP_XI_BINNING_SELECTOR', cv.CAP_PROP_XI_BINNING_SELECTOR),
('CAP_PROP_XI_BINNING_VERTICAL', cv.CAP_PROP_XI_BINNING_VERTICAL),
('CAP_PROP_XI_BPC', cv.CAP_PROP_XI_BPC),
('CAP_PROP_XI_BUFFERS_QUEUE_SIZE', cv.CAP_PROP_XI_BUFFERS_QUEUE_SIZE),
('CAP_PROP_XI_BUFFER_POLICY', cv.CAP_PROP_XI_BUFFER_POLICY),
('CAP_PROP_XI_CC_MATRIX_00', cv.CAP_PROP_XI_CC_MATRIX_00),
('CAP_PROP_XI_CC_MATRIX_01', cv.CAP_PROP_XI_CC_MATRIX_01),
('CAP_PROP_XI_CC_MATRIX_02', cv.CAP_PROP_XI_CC_MATRIX_02),
('CAP_PROP_XI_CC_MATRIX_03', cv.CAP_PROP_XI_CC_MATRIX_03),
('CAP_PROP_XI_CC_MATRIX_10', cv.CAP_PROP_XI_CC_MATRIX_10),
('CAP_PROP_XI_CC_MATRIX_11', cv.CAP_PROP_XI_CC_MATRIX_11),
('CAP_PROP_XI_CC_MATRIX_12', cv.CAP_PROP_XI_CC_MATRIX_12),
('CAP_PROP_XI_CC_MATRIX_13', cv.CAP_PROP_XI_CC_MATRIX_13),
('CAP_PROP_XI_CC_MATRIX_20', cv.CAP_PROP_XI_CC_MATRIX_20),
('CAP_PROP_XI_CC_MATRIX_21', cv.CAP_PROP_XI_CC_MATRIX_21),
('CAP_PROP_XI_CC_MATRIX_22', cv.CAP_PROP_XI_CC_MATRIX_22),
('CAP_PROP_XI_CC_MATRIX_23', cv.CAP_PROP_XI_CC_MATRIX_23),
('CAP_PROP_XI_CC_MATRIX_30', cv.CAP_PROP_XI_CC_MATRIX_30),
('CAP_PROP_XI_CC_MATRIX_31', cv.CAP_PROP_XI_CC_MATRIX_31),
('CAP_PROP_XI_CC_MATRIX_32', cv.CAP_PROP_XI_CC_MATRIX_32),
('CAP_PROP_XI_CC_MATRIX_33', cv.CAP_PROP_XI_CC_MATRIX_33),
('CAP_PROP_XI_CHIP_TEMP', cv.CAP_PROP_XI_CHIP_TEMP),
('CAP_PROP_XI_CMS', cv.CAP_PROP_XI_CMS),
('CAP_PROP_XI_COLOR_FILTER_ARRAY', cv.CAP_PROP_XI_COLOR_FILTER_ARRAY),
('CAP_PROP_XI_COLUMN_FPN_CORRECTION', cv.CAP_PROP_XI_COLUMN_FPN_CORRECTION),
('CAP_PROP_XI_COOLING', cv.CAP_PROP_XI_COOLING),
('CAP_PROP_XI_COUNTER_SELECTOR', cv.CAP_PROP_XI_COUNTER_SELECTOR),
('CAP_PROP_XI_COUNTER_VALUE', cv.CAP_PROP_XI_COUNTER_VALUE),
('CAP_PROP_XI_DATA_FORMAT', cv.CAP_PROP_XI_DATA_FORMAT),
('CAP_PROP_XI_DEBOUNCE_EN', cv.CAP_PROP_XI_DEBOUNCE_EN),
('CAP_PROP_XI_DEBOUNCE_POL', cv.CAP_PROP_XI_DEBOUNCE_POL),
('CAP_PROP_XI_DEBOUNCE_T0', cv.CAP_PROP_XI_DEBOUNCE_T0),
('CAP_PROP_XI_DEBOUNCE_T1', cv.CAP_PROP_XI_DEBOUNCE_T1),
('CAP_PROP_XI_DEBUG_LEVEL', cv.CAP_PROP_XI_DEBUG_LEVEL),
('CAP_PROP_XI_DECIMATION_HORIZONTAL', cv.CAP_PROP_XI_DECIMATION_HORIZONTAL),
('CAP_PROP_XI_DECIMATION_PATTERN', cv.CAP_PROP_XI_DECIMATION_PATTERN),
('CAP_PROP_XI_DECIMATION_SELECTOR', cv.CAP_PROP_XI_DECIMATION_SELECTOR),
('CAP_PROP_XI_DECIMATION_VERTICAL', cv.CAP_PROP_XI_DECIMATION_VERTICAL),
('CAP_PROP_XI_DEFAULT_CC_MATRIX', cv.CAP_PROP_XI_DEFAULT_CC_MATRIX),
('CAP_PROP_XI_DEVICE_MODEL_ID', cv.CAP_PROP_XI_DEVICE_MODEL_ID),
('CAP_PROP_XI_DEVICE_RESET', cv.CAP_PROP_XI_DEVICE_RESET),
('CAP_PROP_XI_DEVICE_SN', cv.CAP_PROP_XI_DEVICE_SN),
('CAP_PROP_XI_DOWNSAMPLING', cv.CAP_PROP_XI_DOWNSAMPLING),
('CAP_PROP_XI_DOWNSAMPLING_TYPE', cv.CAP_PROP_XI_DOWNSAMPLING_TYPE),
('CAP_PROP_XI_EXPOSURE', cv.CAP_PROP_XI_EXPOSURE),
('CAP_PROP_XI_EXPOSURE_BURST_COUNT', cv.CAP_PROP_XI_EXPOSURE_BURST_COUNT),
('CAP_PROP_XI_EXP_PRIORITY', cv.CAP_PROP_XI_EXP_PRIORITY),
('CAP_PROP_XI_FFS_ACCESS_KEY', cv.CAP_PROP_XI_FFS_ACCESS_KEY),
('CAP_PROP_XI_FFS_FILE_ID', cv.CAP_PROP_XI_FFS_FILE_ID),
('CAP_PROP_XI_FFS_FILE_SIZE', cv.CAP_PROP_XI_FFS_FILE_SIZE),
('CAP_PROP_XI_FRAMERATE', cv.CAP_PROP_XI_FRAMERATE),
('CAP_PROP_XI_FREE_FFS_SIZE', cv.CAP_PROP_XI_FREE_FFS_SIZE),
('CAP_PROP_XI_GAIN', cv.CAP_PROP_XI_GAIN),
('CAP_PROP_XI_GAIN_SELECTOR', cv.CAP_PROP_XI_GAIN_SELECTOR),
('CAP_PROP_XI_GAMMAC', cv.CAP_PROP_XI_GAMMAC),
('CAP_PROP_XI_GAMMAY', cv.CAP_PROP_XI_GAMMAY),
('CAP_PROP_XI_GPI_LEVEL', cv.CAP_PROP_XI_GPI_LEVEL),
('CAP_PROP_XI_GPI_MODE', cv.CAP_PROP_XI_GPI_MODE),
('CAP_PROP_XI_GPI_SELECTOR', cv.CAP_PROP_XI_GPI_SELECTOR),
('CAP_PROP_XI_GPO_MODE', cv.CAP_PROP_XI_GPO_MODE),
('CAP_PROP_XI_GPO_SELECTOR', cv.CAP_PROP_XI_GPO_SELECTOR),
('CAP_PROP_XI_HDR', cv.CAP_PROP_XI_HDR),
('CAP_PROP_XI_HDR_KNEEPOINT_COUNT', cv.CAP_PROP_XI_HDR_KNEEPOINT_COUNT),
('CAP_PROP_XI_HDR_T1', cv.CAP_PROP_XI_HDR_T1),
('CAP_PROP_XI_HDR_T2', cv.CAP_PROP_XI_HDR_T2),
('CAP_PROP_XI_HEIGHT', cv.CAP_PROP_XI_HEIGHT),
('CAP_PROP_XI_HOUS_BACK_SIDE_TEMP', cv.CAP_PROP_XI_HOUS_BACK_SIDE_TEMP),
('CAP_PROP_XI_HOUS_TEMP', cv.CAP_PROP_XI_HOUS_TEMP),
('CAP_PROP_XI_HW_REVISION', cv.CAP_PROP_XI_HW_REVISION),
('CAP_PROP_XI_IMAGE_BLACK_LEVEL', cv.CAP_PROP_XI_IMAGE_BLACK_LEVEL),
('CAP_PROP_XI_IMAGE_DATA_BIT_DEPTH', cv.CAP_PROP_XI_IMAGE_DATA_BIT_DEPTH),
('CAP_PROP_XI_IMAGE_DATA_FORMAT', cv.CAP_PROP_XI_IMAGE_DATA_FORMAT),
('CAP_PROP_XI_IMAGE_DATA_FORMAT_RGB32_ALPHA', cv.CAP_PROP_XI_IMAGE_DATA_FORMAT_RGB32_ALPHA),
('CAP_PROP_XI_IMAGE_IS_COLOR', cv.CAP_PROP_XI_IMAGE_IS_COLOR),
('CAP_PROP_XI_IMAGE_PAYLOAD_SIZE', cv.CAP_PROP_XI_IMAGE_PAYLOAD_SIZE),
('CAP_PROP_XI_IS_COOLED', cv.CAP_PROP_XI_IS_COOLED),
('CAP_PROP_XI_IS_DEVICE_EXIST', cv.CAP_PROP_XI_IS_DEVICE_EXIST),
('CAP_PROP_XI_KNEEPOINT1', cv.CAP_PROP_XI_KNEEPOINT1),
('CAP_PROP_XI_KNEEPOINT2', cv.CAP_PROP_XI_KNEEPOINT2),
('CAP_PROP_XI_LED_MODE', cv.CAP_PROP_XI_LED_MODE),
('CAP_PROP_XI_LED_SELECTOR', cv.CAP_PROP_XI_LED_SELECTOR),
('CAP_PROP_XI_LENS_APERTURE_VALUE', cv.CAP_PROP_XI_LENS_APERTURE_VALUE),
('CAP_PROP_XI_LENS_FEATURE', cv.CAP_PROP_XI_LENS_FEATURE),
('CAP_PROP_XI_LENS_FEATURE_SELECTOR', cv.CAP_PROP_XI_LENS_FEATURE_SELECTOR),
('CAP_PROP_XI_LENS_FOCAL_LENGTH', cv.CAP_PROP_XI_LENS_FOCAL_LENGTH),
('CAP_PROP_XI_LENS_FOCUS_DISTANCE', cv.CAP_PROP_XI_LENS_FOCUS_DISTANCE),
('CAP_PROP_XI_LENS_FOCUS_MOVE', cv.CAP_PROP_XI_LENS_FOCUS_MOVE),
('CAP_PROP_XI_LENS_FOCUS_MOVEMENT_VALUE', cv.CAP_PROP_XI_LENS_FOCUS_MOVEMENT_VALUE),
('CAP_PROP_XI_LENS_MODE', cv.CAP_PROP_XI_LENS_MODE),
('CAP_PROP_XI_LIMIT_BANDWIDTH', cv.CAP_PROP_XI_LIMIT_BANDWIDTH),
('CAP_PROP_XI_LUT_EN', cv.CAP_PROP_XI_LUT_EN),
('CAP_PROP_XI_LUT_INDEX', cv.CAP_PROP_XI_LUT_INDEX),
('CAP_PROP_XI_LUT_VALUE', cv.CAP_PROP_XI_LUT_VALUE),
('CAP_PROP_XI_MANUAL_WB', cv.CAP_PROP_XI_MANUAL_WB),
('CAP_PROP_XI_OFFSET_X', cv.CAP_PROP_XI_OFFSET_X),
('CAP_PROP_XI_OFFSET_Y', cv.CAP_PROP_XI_OFFSET_Y),
('CAP_PROP_XI_OUTPUT_DATA_BIT_DEPTH', cv.CAP_PROP_XI_OUTPUT_DATA_BIT_DEPTH),
('CAP_PROP_XI_OUTPUT_DATA_PACKING', cv.CAP_PROP_XI_OUTPUT_DATA_PACKING),
('CAP_PROP_XI_OUTPUT_DATA_PACKING_TYPE', cv.CAP_PROP_XI_OUTPUT_DATA_PACKING_TYPE),
('CAP_PROP_XI_RECENT_FRAME', cv.CAP_PROP_XI_RECENT_FRAME),
('CAP_PROP_XI_REGION_MODE', cv.CAP_PROP_XI_REGION_MODE),
('CAP_PROP_XI_REGION_SELECTOR', cv.CAP_PROP_XI_REGION_SELECTOR),
('CAP_PROP_XI_ROW_FPN_CORRECTION', cv.CAP_PROP_XI_ROW_FPN_CORRECTION),
('CAP_PROP_XI_SENSOR_BOARD_TEMP', cv.CAP_PROP_XI_SENSOR_BOARD_TEMP),
('CAP_PROP_XI_SENSOR_CLOCK_FREQ_HZ', cv.CAP_PROP_XI_SENSOR_CLOCK_FREQ_HZ),
('CAP_PROP_XI_SENSOR_CLOCK_FREQ_INDEX', cv.CAP_PROP_XI_SENSOR_CLOCK_FREQ_INDEX),
('CAP_PROP_XI_SENSOR_DATA_BIT_DEPTH', cv.CAP_PROP_XI_SENSOR_DATA_BIT_DEPTH),
('CAP_PROP_XI_SENSOR_FEATURE_SELECTOR', cv.CAP_PROP_XI_SENSOR_FEATURE_SELECTOR),
('CAP_PROP_XI_SENSOR_FEATURE_VALUE', cv.CAP_PROP_XI_SENSOR_FEATURE_VALUE),
('CAP_PROP_XI_SENSOR_MODE', cv.CAP_PROP_XI_SENSOR_MODE),
('CAP_PROP_XI_SENSOR_OUTPUT_CHANNEL_COUNT', cv.CAP_PROP_XI_SENSOR_OUTPUT_CHANNEL_COUNT),
('CAP_PROP_XI_SENSOR_TAPS', cv.CAP_PROP_XI_SENSOR_TAPS),
('CAP_PROP_XI_SHARPNESS', cv.CAP_PROP_XI_SHARPNESS),
('CAP_PROP_XI_SHUTTER_TYPE', cv.CAP_PROP_XI_SHUTTER_TYPE),
('CAP_PROP_XI_TARGET_TEMP', cv.CAP_PROP_XI_TARGET_TEMP),
('CAP_PROP_XI_TEST_PATTERN', cv.CAP_PROP_XI_TEST_PATTERN),
('CAP_PROP_XI_TEST_PATTERN_GENERATOR_SELECTOR', cv.CAP_PROP_XI_TEST_PATTERN_GENERATOR_SELECTOR),
('CAP_PROP_XI_TIMEOUT', cv.CAP_PROP_XI_TIMEOUT),
('CAP_PROP_XI_TRANSPORT_PIXEL_FORMAT', cv.CAP_PROP_XI_TRANSPORT_PIXEL_FORMAT),
('CAP_PROP_XI_TRG_DELAY', cv.CAP_PROP_XI_TRG_DELAY),
('CAP_PROP_XI_TRG_SELECTOR', cv.CAP_PROP_XI_TRG_SELECTOR),
('CAP_PROP_XI_TRG_SOFTWARE', cv.CAP_PROP_XI_TRG_SOFTWARE),
('CAP_PROP_XI_TRG_SOURCE', cv.CAP_PROP_XI_TRG_SOURCE),
('CAP_PROP_XI_TS_RST_MODE', cv.CAP_PROP_XI_TS_RST_MODE),
('CAP_PROP_XI_TS_RST_SOURCE', cv.CAP_PROP_XI_TS_RST_SOURCE),
('CAP_PROP_XI_USED_FFS_SIZE', cv.CAP_PROP_XI_USED_FFS_SIZE),
('CAP_PROP_XI_WB_KB', cv.CAP_PROP_XI_WB_KB),
('CAP_PROP_XI_WB_KG', cv.CAP_PROP_XI_WB_KG),
('CAP_PROP_XI_WB_KR', cv.CAP_PROP_XI_WB_KR),
('CAP_PROP_XI_WIDTH', cv.CAP_PROP_XI_WIDTH),
('CAP_PROP_ZOOM', cv.CAP_PROP_ZOOM),
('CAP_PVAPI', cv.CAP_PVAPI),
('CAP_PVAPI_DECIMATION_2OUTOF16', cv.CAP_PVAPI_DECIMATION_2OUTOF16),
('CAP_PVAPI_DECIMATION_2OUTOF4', cv.CAP_PVAPI_DECIMATION_2OUTOF4),
('CAP_PVAPI_DECIMATION_2OUTOF8', cv.CAP_PVAPI_DECIMATION_2OUTOF8),
('CAP_PVAPI_DECIMATION_OFF', cv.CAP_PVAPI_DECIMATION_OFF),
('CAP_PVAPI_FSTRIGMODE_FIXEDRATE', cv.CAP_PVAPI_FSTRIGMODE_FIXEDRATE),
('CAP_PVAPI_FSTRIGMODE_FREERUN', cv.CAP_PVAPI_FSTRIGMODE_FREERUN),
('CAP_PVAPI_FSTRIGMODE_SOFTWARE', cv.CAP_PVAPI_FSTRIGMODE_SOFTWARE),
('CAP_PVAPI_FSTRIGMODE_SYNCIN1', cv.CAP_PVAPI_FSTRIGMODE_SYNCIN1),
('CAP_PVAPI_FSTRIGMODE_SYNCIN2', cv.CAP_PVAPI_FSTRIGMODE_SYNCIN2),
('CAP_PVAPI_PIXELFORMAT_BAYER16', cv.CAP_PVAPI_PIXELFORMAT_BAYER16),
('CAP_PVAPI_PIXELFORMAT_BAYER8', cv.CAP_PVAPI_PIXELFORMAT_BAYER8),
('CAP_PVAPI_PIXELFORMAT_BGR24', cv.CAP_PVAPI_PIXELFORMAT_BGR24),
('CAP_PVAPI_PIXELFORMAT_BGRA32', cv.CAP_PVAPI_PIXELFORMAT_BGRA32),
('CAP_PVAPI_PIXELFORMAT_MONO16', cv.CAP_PVAPI_PIXELFORMAT_MONO16),
('CAP_PVAPI_PIXELFORMAT_MONO8', cv.CAP_PVAPI_PIXELFORMAT_MONO8),
('CAP_PVAPI_PIXELFORMAT_RGB24', cv.CAP_PVAPI_PIXELFORMAT_RGB24),
('CAP_PVAPI_PIXELFORMAT_RGBA32', cv.CAP_PVAPI_PIXELFORMAT_RGBA32),
('CAP_QT', cv.CAP_QT),
('CAP_REALSENSE', cv.CAP_REALSENSE),
('CAP_UEYE', cv.CAP_UEYE),
('CAP_UNICAP', cv.CAP_UNICAP),
('CAP_V4L', cv.CAP_V4L),
('CAP_V4L2', cv.CAP_V4L2),
('CAP_VFW', cv.CAP_VFW),
('CAP_WINRT', cv.CAP_WINRT),
('CAP_XIAPI', cv.CAP_XIAPI),
('CAP_XINE', cv.CAP_XINE)
]



WRITABLE_CAPS_C270 = [
('CAP_PROP_SETTINGS', cv.CAP_PROP_SETTINGS),
('CAP_PROP_FPS', cv.CAP_PROP_FPS),
('CAP_PROP_FRAME_HEIGHT', cv.CAP_PROP_FRAME_HEIGHT),
('CAP_PROP_FRAME_WIDTH', cv.CAP_PROP_FRAME_WIDTH),
('CAP_PROP_AUTO_WB', cv.CAP_PROP_AUTO_WB),
('CAP_PROP_BACKLIGHT', cv.CAP_PROP_BACKLIGHT),
('CAP_PROP_BRIGHTNESS', cv.CAP_PROP_BRIGHTNESS),
('CAP_PROP_CONTRAST', cv.CAP_PROP_CONTRAST),
('CAP_PROP_EXPOSURE', cv.CAP_PROP_EXPOSURE),
('CAP_INTELPERC_IMAGE', cv.CAP_INTELPERC_IMAGE),
('CAP_OPENNI_BGR_IMAGE', cv.CAP_OPENNI_BGR_IMAGE),
('CAP_OPENNI_DISPARITY_MAP_32F', cv.CAP_OPENNI_DISPARITY_MAP_32F),
('CAP_OPENNI_GRAY_IMAGE', cv.CAP_OPENNI_GRAY_IMAGE),
('CAP_OPENNI_QVGA_30HZ', cv.CAP_OPENNI_QVGA_30HZ),
('CAP_OPENNI_QVGA_60HZ', cv.CAP_OPENNI_QVGA_60HZ),
('CAP_OPENNI_VALID_DEPTH_MASK', cv.CAP_OPENNI_VALID_DEPTH_MASK),
('CAP_PROP_AUTO_EXPOSURE', cv.CAP_PROP_AUTO_EXPOSURE),
('CAP_PROP_SATURATION', cv.CAP_PROP_SATURATION),
('CAP_PROP_SHARPNESS', cv.CAP_PROP_SHARPNESS),
('CAP_PROP_CONVERT_RGB', cv.CAP_PROP_CONVERT_RGB),
('CAP_PROP_FOURCC', cv.CAP_PROP_FOURCC),
('CAP_PROP_GAIN', cv.CAP_PROP_GAIN),
('CAP_PROP_WHITE_BALANCE_BLUE_U', cv.CAP_PROP_WHITE_BALANCE_BLUE_U),
('CAP_PVAPI_DECIMATION_2OUTOF8', cv.CAP_PVAPI_DECIMATION_2OUTOF8),
('CAP_PVAPI_FSTRIGMODE_FIXEDRATE', cv.CAP_PVAPI_FSTRIGMODE_FIXEDRATE),
('CAP_PVAPI_FSTRIGMODE_SOFTWARE', cv.CAP_PVAPI_FSTRIGMODE_SOFTWARE),
('CAP_PVAPI_PIXELFORMAT_BAYER16', cv.CAP_PVAPI_PIXELFORMAT_BAYER16),
('CAP_PVAPI_PIXELFORMAT_BAYER8', cv.CAP_PVAPI_PIXELFORMAT_BAYER8),
('CAP_PVAPI_PIXELFORMAT_BGR24', cv.CAP_PVAPI_PIXELFORMAT_BGR24),
('CAP_PVAPI_PIXELFORMAT_RGB24', cv.CAP_PVAPI_PIXELFORMAT_RGB24)
]


WRITABLE_CAPS_C920 = [
('CAP_PROP_SETTINGS', cv.CAP_PROP_SETTINGS),
('CAP_PROP_FPS', cv.CAP_PROP_FPS),
('CAP_PROP_FRAME_HEIGHT', cv.CAP_PROP_FRAME_HEIGHT),
('CAP_PROP_FRAME_WIDTH', cv.CAP_PROP_FRAME_WIDTH),
('CAP_PROP_AUTO_EXPOSURE', cv.CAP_PROP_AUTO_EXPOSURE),
('CAP_PROP_AUTO_WB', cv.CAP_PROP_AUTO_WB),
('CAP_PROP_AUTOFOCUS', cv.CAP_PROP_AUTOFOCUS),
('CAP_PROP_BACKLIGHT', cv.CAP_PROP_BACKLIGHT),
('CAP_PROP_BRIGHTNESS', cv.CAP_PROP_BRIGHTNESS),
('CAP_PROP_SATURATION', cv.CAP_PROP_SATURATION),
('CAP_PROP_SHARPNESS', cv.CAP_PROP_SHARPNESS),
('CAP_PROP_CONTRAST', cv.CAP_PROP_CONTRAST),
('CAP_PROP_EXPOSURE', cv.CAP_PROP_EXPOSURE),
('CAP_PROP_FOCUS', cv.CAP_PROP_FOCUS),
('CAP_PROP_ZOOM', cv.CAP_PROP_ZOOM),
('CAP_PROP_WHITE_BALANCE_BLUE_U', cv.CAP_PROP_WHITE_BALANCE_BLUE_U),
('CAP_INTELPERC_IMAGE', cv.CAP_INTELPERC_IMAGE),
('CAP_OPENNI_BGR_IMAGE', cv.CAP_OPENNI_BGR_IMAGE),
('CAP_OPENNI_GRAY_IMAGE', cv.CAP_OPENNI_GRAY_IMAGE),
('CAP_OPENNI_DISPARITY_MAP_32F', cv.CAP_OPENNI_DISPARITY_MAP_32F),
('CAP_OPENNI_QVGA_30HZ', cv.CAP_OPENNI_QVGA_30HZ),
('CAP_OPENNI_QVGA_60HZ', cv.CAP_OPENNI_QVGA_60HZ),
('CAP_OPENNI_VALID_DEPTH_MASK', cv.CAP_OPENNI_VALID_DEPTH_MASK),
('CAP_PROP_CONVERT_RGB', cv.CAP_PROP_CONVERT_RGB),
('CAP_PROP_FOURCC', cv.CAP_PROP_FOURCC),
('CAP_PROP_GAIN', cv.CAP_PROP_GAIN),
('CAP_PROP_PAN', cv.CAP_PROP_PAN),
('CAP_PROP_TILT', cv.CAP_PROP_TILT),
('CAP_PVAPI_DECIMATION_2OUTOF8', cv.CAP_PVAPI_DECIMATION_2OUTOF8),
('CAP_PVAPI_FSTRIGMODE_FIXEDRATE', cv.CAP_PVAPI_FSTRIGMODE_FIXEDRATE),
('CAP_PVAPI_FSTRIGMODE_SOFTWARE', cv.CAP_PVAPI_FSTRIGMODE_SOFTWARE),
('CAP_PVAPI_PIXELFORMAT_BAYER16', cv.CAP_PVAPI_PIXELFORMAT_BAYER16),
('CAP_PVAPI_PIXELFORMAT_BAYER8', cv.CAP_PVAPI_PIXELFORMAT_BAYER8),
('CAP_PVAPI_PIXELFORMAT_BGR24', cv.CAP_PVAPI_PIXELFORMAT_BGR24),
('CAP_PVAPI_PIXELFORMAT_RGB24', cv.CAP_PVAPI_PIXELFORMAT_RGB24)
]



    



#TODO: FIND AND SET CAMERA INDEX

graph = FilterGraph()

devices = graph.get_input_devices()

for i, name in enumerate(devices):
    print(f"[{i}] {name}")



cam_idx = 2
webcam = devices[cam_idx]


cap = cv.VideoCapture(cam_idx, cv.CAP_DSHOW) 


settings = False

try:
    settings = cap.set(cv.CAP_PROP_SETTINGS, 1.0)
    print("Settings Status is:", settings)
except:
    print("Settings Status is:", settings)



cv.namedWindow(webcam, cv.WINDOW_KEEPRATIO)


while cap.isOpened():

    ret, frame = cap.read()
    
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    
    frame = draw_info(cap, frame, WRITABLE_CAPS_C920)

    cv.imshow(webcam, frame)

    if cv.waitKey(1) & 0xFF == 27:
        break


print("Camera is closing")

cap.release()

cv.destroyAllWindows()

